### ISSUE TITLE
Testing cervical model on `hc-leipzig-7t-mp2rage` dataset

### ISSUE THREAD

**Issue by KaterinaKrejci231054** [ivadomed/model-spinal-rootlets#63] opened 2024-07-05 14:29 UTC
This issue describes the application of the model [r20240523](https://github.com/ivadomed/model-spinal-rootlets/releases/tag/r20240523) (for dorsal and ventral rootlets) to images from the `hc-leipzig-7t-mp2rage` dataset.

Related: https://github.com/ivadomed/model-spinal-rootlets/issues/45

# Processing steps
## Testing rootlet segmentation on raw data 
For each subject, 3 raw nifti files are provided (labeled as UNIT1, inv-1_part-mag_MP2RAGE, inv-2_part-mag_MP2RAGE). I tried to test the [r20240523](https://github.com/ivadomed/model-spinal-rootlets/releases/tag/r20240523) model on these data, but no rootlets segmentation was created (see below):
#### UNIT1:
![sub-sspr20_UNIT1_label-rootlets_dseg](https://github.com/ivadomed/model-spinal-rootlets/assets/78610729/94ca0433-b20b-400b-9d9e-ab217c04c7e0)

#### inv-1_part-mag_MP2RAGE:
![sub-sspr20_inv-1_part-mag_MP2RAGE_label-rootlets_dseg](https://github.com/ivadomed/model-spinal-rootlets/assets/78610729/54015e26-df14-4eca-a696-00bd87b9bda0)

#### inv-2_part-mag_MP2RAGE:
![sub-sspr20_inv-2_part-mag_MP2RAGE_label-rootlets_dseg](https://github.com/ivadomed/model-spinal-rootlets/assets/78610729/618e6e5d-897e-4e08-b863-724af3aeb49d)

## Testing rootlets segmentation on inverse data 
Then, I tried to create inverse images (multiplied by `-1`). The only rootlets segmentation was created on the UNIT1 inverse image (see below):
![sub-sspr20_UNIT1_neg_label-rootlets_dseg](https://github.com/ivadomed/model-spinal-rootlets/assets/78610729/900a37e7-ed33-48f7-96f2-cda061aaa349)

**Comment by KaterinaKrejci231054** [comment] 2024-07-09 16:50
Gifs of 3 subjects (inverted UNIT1 data) with rootlets segmentation (sub-18, sub-22 and sub-30):

#### sub-18:
![sub-118](https://github.com/ivadomed/model-spinal-rootlets/assets/78610729/68c24845-66d7-40d3-ae4b-83ff3da08b40)

#### sub-22:
![sub-122](https://github.com/ivadomed/model-spinal-rootlets/assets/78610729/cb5baf6d-6eb3-4a39-8a69-fb43149b072d)

#### sub-30:
![sub-30](https://github.com/ivadomed/model-spinal-rootlets/assets/78610729/9ea154fa-010c-4132-b32c-df3316c6b313)

**Comment by valosekj** [comment] 2024-07-09 17:12
Thanks for testing the model @KaterinaKrejci231054! The predictions for the inverted UNIT1 image (multiplied by -1) look promising! I believe we can leverage them for the model training. I would do the following steps:

1. run the model on inverted UNIT1 images for 5 subjects to get initial rootlets segmentations
2. correct the predictions; push them to git-annex
3. train an initial nnUNet model using all contrasts (`UNIT1`, `inv-1_part-mag_MP2RAGE`, `inv-2_part-mag_MP2RAGE`). A big advantage here is that the contrasts are already coregistered, so we can use the same GT for all 3 contrasts. 

Note that the recommended nnUNet trainer now is `nnU-Net ResEnc L`; see [here](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/resenc_presets.md#point_right-we-recommend-nnu-net-resenc-l-as-the-new-default-nnu-net-configuration-point_left). We can this train two models: one with the default trainer, the second with the `nnU-Net ResEnc L` trainer.

@jcohenadad, what do you think?

**Comment by jcohenadad** [comment] 2024-07-09 17:19
Excellent plan, thank you!

p.s. looks like the top right rootlets are missing for `sub-30` but I'm sure you are aware

**Comment by valosekj** [comment] 2024-07-09 17:50
> Excellent plan, thank you!

Great, thank you for the confirmation! @KaterinaKrejci231054 will work on it.

> p.s. looks like the top right rootlets are missing for `sub-30` but I'm sure you are aware

Yes, we are aware of this. After running the inference, we will go through the predictions and correct them.

**Comment by jcohenadad** [comment] 2024-07-09 17:56
just throwing this out there, because we talk about doing additional GT: https://github.com/ivadomed/model-spinal-rootlets/issues/59#issuecomment-2218325320

**Comment by valosekj** [comment] 2024-07-10 17:45
> Each contrast shows different shapes of rootlets (see below)

Interesting! This can be caused by different inversion times for inv-1 and inv-2.

> we need to consider which contrast to use for manual corrections of the rootlet segmentation. Maybe we can use all the contrasts and make only one corrected segmentation.

Yeah. This sounds good. Let's try to leverage information from all contrasts to make one good segmentation. Then, this single segmentation can be reused for all contrasts to train a single model segmenting all MP2RAGE contrasts.

**Comment by valosekj** [comment] 2024-07-13 22:42
Model training continues as part of https://github.com/ivadomed/model-spinal-rootlets/issues/65

--> closing this issue

**Closed by valosekj** 2024-07-13 22:42 UTC
Labels: contrast: MP2RAGE, strength: 7T
