### ISSUE TITLE
Obtain spinal levels from nerve rootlets segmentation

### ISSUE THREAD

**Issue by tzebre** [ivadomed/model-spinal-rootlets#13] opened 2023-08-14 18:11 UTC
UPDATE by @valosekj -- I updated the issue description to be in line with https://github.com/ivadomed/model-spinal-rootlets/pull/18.

The model predicts spinal nerve rootlets segmentation; see [here](https://github.com/ivadomed/model-spinal-rootlets#model-overview). The predicted spinal nerve rootlets can be used to obtain the spinal levels using the [utilities/rootlets_to_spinal_levels.py](https://github.com/ivadomed/model-spinal-rootlets/blob/jv/refactor_utilities_folder/utilities/rootlets_to_spinal_levels.py) script using the following procedure:

1. Dilate the spinal cord segmentation by 1, 2 or 3 voxels ([`-dilate` input argument](https://github.com/ivadomed/model-spinal-rootlets/blob/jv/refactor_utilities_folder/utilities/rootlets_to_spinal_levels.py#L60-L67)) 
2. Find the intersection between the dilated spinal cord segmentation and the rootlets segmentation. 
3. The spinal levels are then defined based on the top and bottom slices of the intersection.

Individual steps are illustrated in [this](https://docs.google.com/presentation/d/1z_2gLv_ps5eq6nvSqKVcBFijbj2pZa4N79Y1NRaVTmU/edit?usp=sharing) Google Slides presentation.

---

To validate the result, we compared the results of this prediction with [Cadotte et al., 2017](https://pubmed.ncbi.nlm.nih.gov/25523587/) values using the same MRI images. 
Cadotte data have labeled images with PMJ (pontomedullary junction), vertebrae and DREZ (dorsal root entry zone) labeled in the same file. I used [separate_cadotte_label.py](https://github.com/ivadomed/model-spinal-rootlets/blob/main/utilities/separate_cadotte_label.py) to create 3 files: one for the PMJ, one for the DREZ, and one for vertebrae. 
I've used [cadotte_value notebook](https://github.com/ivadomed/model-spinal-rootlets/blob/main/utilities/cadotte_value.ipynb) to create [cadotte_dist.csv](https://github.com/ivadomed/model-spinal-rootlets/blob/main/dataset_creation/cadotte_dist.csv)
The results of the prediction on Cadotte are not really good #11. 

<details><summary>**Cadotte paper graph**</summary>

<img width="1059" alt="Capture d’écran 2023-08-15 à 15 24 59" src="https://github.com/ivadomed/model-spinal-rootlets/assets/58122097/7c9caed4-fcde-444d-ad77-bd5dd8d25db8">

</details>

<details><summary>**Reproduced graph**</summary>

<img width="917" alt="final image" src="https://github.com/ivadomed/model-spinal-rootlets/assets/58122097/c43d68dd-951f-42aa-b0c1-33fa58e2e8ff">

_Legend: Left = Cadotte DREZ label, Middle = Cadotte label vertebrae, Right = M3 prediction (conversion with dilate = 2)_

</details>

**Comment by valosekj** [comment] 2023-10-01 07:45
Raphaëlle Schlienger noticed that some subjects have nerve rootlets segmentation quite far from the spinal cord, which thus leads to "short" spinal levels.
In such cases, I would recommend increasing the dilation of the spinal cord to [`-dilate 3`](https://github.com/ivadomed/model-spinal-rootlets/blob/jv/refactor_utilities_folder/utilities/rootlets_to_spinal_levels.py#L60-L67):

![image](https://github.com/ivadomed/model-spinal-rootlets/assets/39456460/286d7f72-742c-4acb-bf77-397e010b7890)
_Legend: blue - dilate3, red - dilate2_

**Comment by valosekj** [comment] 2023-10-01 08:31
@jcohenadad proposed an idea to take the highest Z value (i.e., in superior-inferior direction) found for each spinal nerve rootlet level. Given that rootlets are oriented caudally as they go away from the cord (see image below), the most rostral point of the segmented rootlets should be the closest to the actual spinal level.

![](https://www.ncbi.nlm.nih.gov/pmc/articles/instance/7964298/bin/zj40041541920002.jpg)
Image [source](https://pubmed.ncbi.nlm.nih.gov/25523587/#&gid=article-figures&pid=fig-2-uid-1)

But, this might not work for C1 and C2 as these rootlets are "upside down" compared to the other rootlets.

**Comment by RaphaSchl** [comment] 2023-10-02 14:28
This means you would be taking the highest Z-value to define the start of the spinal level. 
But this highest Z-value is when we 'lose sight' of the rootlet as it enters the white+grey matter area. Yet we can imagine it still has to cross through white matter before synapsing in the innermost grey matter of the cord (butterfly shape on the right MERGE/MEDIC T2* image).

![T2_medic_spinalrootlets](https://github.com/ivadomed/model-spinal-rootlets/assets/62699870/230dcff0-90ab-4ce9-9f5a-18bd92771ff3)

Hence some activity linked to that spinal level may occur above the highest Z-value observed for the corresponding rootlet. And with a precision of 0.8mm iso as in this T2 image used as reference (on the left), we can't be sure we are ultimately observing the highest point of entry.

Maybe the spinal levels should thus start a bit above this highest Z-value to account for this uncertainty?

**Comment by jcohenadad** [comment] 2023-10-02 14:51
> But this highest Z-value is when we 'lose sight' of the rootlet as it enters the white+grey matter area.

Yes, I agree. This is precisely the reasoning for selecting the highest z-value (vs. doing the dilation). Even though the "highest z-value" is not perfect because as you pointed out, we don't exactly know where the dorsal entries synapse inside the cord, this is the closest "bet" we can make given the coarse resolution of MRI. 

> Maybe the spinal levels should thus start a bit above this highest Z-value to account for this uncertainty

Sure, but what is "a bit above"? We would need some quantitative evidence to come up with a model that would systematically "shift up" the suggested spinal levels. Without this quantitative evidence, IMHO the best we can do is to rely on what we "see" on the MRI.

**Comment by sandrinebedard** [comment] 2023-10-02 16:37
> Sure, but what is "a bit above"? We would need some quantitative evidence to come up with a model that would systematically "shift up" the suggested spinal levels. Without this quantitative evidence, IMHO the best we can do is to rely on what we "see" on the MRI.

> Maybe the Mendez et al. paper (see [spinalcordtoolbox/PAM50#3](https://github.com/spinalcordtoolbox/PAM50/pull/3)) includes such useful information? E.g. exact location of spinal levels based on the visualization of the nerve rootlets visible before they enter the spinal cord. @sandrinebedard might have some insights about this

In the Mendez we have **Width Across Dorsal and Ventral Columns** (between the nerve root entry) and you have the angles of rostral and caudal rootlets per level, maybe with that you could compute the extra z you should add!

However, you need to consider that the angles of the rootlets changes with flexion/extension of the head, so it may not be accurate.

**Comment by jcohenadad** [comment] 2023-10-02 19:17
> In the Mendez we have Width Across Dorsal and Ventral Columns (between the nerve root entry) and you have the angles of rostral and caudal rootlets per level, maybe with that you could compute the extra z you should add!

Brilliant idea! That would be very cool indeed. Though it might not be super robust to estimate an angle based on a very noisy segmentation. What might be much more robust would be to fit a geometric model of the rootlets to the segmented labels. 

For example, we could segment the rootlets in the PAM50 space. Then, for every new subject, do:
- segmentation of nerve rootlets in native space
- registration to PAM50
- bring rootlets segmentation from native space to PAM50 space
- label-wise registration between PAM50 rootlets and subject rootlets (this could be a Tz-only registration, and we could potentially use some regularization across all rootlets registration because all rootlets are somewhat geometrically linked)
- concatenate transformation PAM50rootlets --> nativeRootletsInPAM50space --> nativeRootletsInNativeSpace
- get the spinal levels from the PAM50 (defined with [Frostell et al](https://github.com/spinalcordtoolbox/PAM50/pull/18).) and apply the inverse transform PAM50levels --> PAM50levelsInNativeSpace

**Comment by valosekj** [comment] 2023-10-04 16:11
I am working on the solution described in the [previous comment](https://github.com/ivadomed/model-spinal-rootlets/issues/13#issuecomment-1743615563). So far, I have:

1. segmented the spinal nerve rootlets in the PAM50 T2w image (by running our nnUNet model) -- prediction looks pretty good:

![Kapture 2023-10-04 at 11 34 35](https://github.com/ivadomed/model-spinal-rootlets/assets/39456460/4338d20c-6e01-40a5-91ee-3e208e89469e)

2. segmented the spinal nerve rootlets in the native space -- here I use `sub-007_ses-headNormal` and the STAPLE reference segmentation (`sub-007_ses-headNormal_T2w_label-rootlet_staple.nii.gz`) obtained from four raters (details in [#17](https://github.com/ivadomed/model-spinal-rootlets/issues/17))

3. registered the native T2w image to PAM50 template:

```console
file_t2=sub-007_ses-headNormal_T2w

# Segment spinal cord
sct_deepseg_sc -i ${file_t2}.nii.gz -c t2 -qc qc -qc-subject ${file_t2}

# Create mid-vertebral labels in the cord for vertebrae C3 and C5 
sct_label_vertebrae -i ${file_t2}.nii.gz -s ${file_t2}_seg.nii.gz -c t2 -qc qc -qc-subject ${file_t2}
sct_label_utils -i ${file_t2}_seg_labeled.nii.gz -vert-body 3,5 -o ${file_t2}_seg_labeled_vertbody_35.nii.gz -qc qc -qc-subject ${file_t2}

# Register T2-w image to PAM50 template
sct_register_to_template -i ${file_t2}.nii.gz -s ${file_t2}_seg.nii.gz -l ${file_t2}_seg_labeled_vertbody_35.nii.gz -c t2 -param step=1,type=seg,algo=centermassrot:step=2,type=seg,algo=syn,slicewise=1,smooth=0,iter=5:step=3,type=im,algo=syn,slicewise=1,smooth=0,iter=3 -qc qc -qc-subject ${file_t2}

# Rename output for clarity
mv anat2template.nii.gz ${file_t2}_reg.nii.gz
```

4. brought rootlets segmentation from native space to PAM50 space:

```console
# Bring rootlets segmentation from native space to PAM50 space
# Note: Nearest-neighbor interpolation (-x nn) must be used to preserve the level-wise rootlets segmentation values
sct_apply_transfo -i ${file_t2}_label-rootlet_staple.nii.gz -d $SCT_DIR/data/PAM50/template/PAM50_t2.nii.gz -w warp_anat2template.nii.gz -x nn
```

![Kapture 2023-10-04 at 11 45 16](https://github.com/ivadomed/model-spinal-rootlets/assets/39456460/d39aae84-8bd9-4676-9717-4c90aea5b43a)

_Legend: red - PAM50 rootlets, blue - native rootlets registered to PAM50_

Now, I am working on the label-wise registration between PAM50 rootlets and subject rootlets. TODO - add details.

**Comment by jcohenadad** [comment] 2023-10-04 20:41
I also think this should be debated during SCT's course "discussion period"

**Comment by valosekj** [comment] 2023-10-06 13:25
Following up on my [previous comment](https://github.com/ivadomed/model-spinal-rootlets/issues/13#issuecomment-1747225497), I am currently working on the label-wise Tz-only registration between PAM50 rootlets and subject rootlets.

Since `sct_register_multimodal` has limited flexibility in controlling its `step=0`, I am continuing directly with `$SCT_DIR/bin/isct_antsRegistration`. 
The following command combining Affine and BSplineSyN registrations produces promising results!

```console
$SCT_DIR/bin/isct_antsRegistration --dimensionality 3 --float 0 \
--output '[step0,sub-007_ses-headNormal_T2w_label-rootlet_staple_reg_reg.nii.gz]' --interpolation 'nearestNeighbor' --verbose 1 \
--transform 'Affine[5]' --metric 'MeanSquares[PAM50_t2_label-rootlet.nii.gz,sub-007_ses-headNormal_T2w_label-rootlet_staple_reg.nii.gz,1,32]' --convergence 20x10 --shrink-factors 2x1 --smoothing-sigmas 0x0mm --shrink-factors 1x1 --restrict-deformation 0x0x1 \
--transform 'BSplineSyN[0.1,3,0]' --metric 'MeanSquares[PAM50_t2_label-rootlet.nii.gz,sub-007_ses-headNormal_T2w_label-rootlet_staple_reg.nii.gz,1,32]' --convergence 10x5 --shrink-factors 2x1 --smoothing-sigmas 0x0mm --shrink-factors 1x1 --restrict-deformation 0x0x1
```

Notice the shift in S-I direction between the blue (before the Tz-only registration) and green (after the Tz-only registration). The green is now much closer to red (PAM50 rootlets)!

![Kapture 2023-10-06 at 09 19 41](https://github.com/ivadomed/model-spinal-rootlets/assets/39456460/0615df17-d13b-4fd1-ac79-4668fbbc0c3b)

_Legend: red - PAM50 rootlets, blue - native rootlets registered to PAM50, green -  native rootlets registered to PAM50 after the second (Tz-only) registration_

**Comment by valosekj** [comment] 2023-10-06 19:10
Continuing:

[`$SCT_DIR/bin/isct_antsRegistration`](https://github.com/ivadomed/model-spinal-rootlets/issues/13#issuecomment-1750678688) outputted the following files:

```
registration2_1InverseWarp.nii.gz       # PAM50rootlets --> nativeRootletsInPAM50space -- using this one
registration2_1Warp.nii.gz              # nativeRootletsInPAM50space --> PAM50rootlets 
registration2_0GenericAffine.mat
```

6. concatenate PAM50rootlets --> nativeRootletsInPAM50space (`registration2_1InverseWarp.nii.gz`) and nativeRootletsInPAM50space --> nativeRootletsInNativeSpace (`warp_template2anat.nii.gz`)  transformations to obtain a single warping field (PAM50rootlets --> nativeRootletsInNativeSpace):

```console
file_t2=sub-007_ses-headNormal_T2w

sct_concat_transfo -d ${file_t2}.nii.gz -w registration2_1InverseWarp.nii.gz warp_template2anat.nii.gz -o warp_final.nii.gz
```

7. get spinal levels from Frostell et al. paper (see [PR #18](https://github.com/spinalcordtoolbox/PAM50/pull/18)):

```console
cd ~/code/PAM50
git pull
git checkout jca/16-spinal-levels
```

8. bring PAM50 spinal levels (`template/PAM50_spinal_levels.nii.gz`) from PAM50 template space to subject native space using the concatenated transformation:

```console
sct_apply_transfo -i ~/code/PAM50/template/PAM50_spinal_levels.nii.gz -d ${file_t2}.nii.gz -w warp_final.nii.gz -x nn
```

Resulting native image and native rootlets with registered `PAM50_spinal_levels.nii.gz`:

![Kapture 2023-10-06 at 15 06 36](https://github.com/ivadomed/model-spinal-rootlets/assets/39456460/545550d9-3d62-49dd-8203-f1d880db462e)

**Comment by jcohenadad** [comment] 2023-10-06 19:15
omg this is amazing, great job @valosekj 🏅 👏!!!  I could watch that video for hours. Let's make a similar one for SCT course where you go back-and-forth along AP in the coronal plane.

**Comment by valosekj** [comment] 2023-10-09 19:09
erratum to my [previous point](https://github.com/ivadomed/model-spinal-rootlets/issues/13#issuecomment-1751289800) about warping field concatenation:

> [`$SCT_DIR/bin/isct_antsRegistration`](https://github.com/ivadomed/model-spinal-rootlets/issues/13#issuecomment-1750678688) outputted the following files:
>
>```
>registration2_1InverseWarp.nii.gz       # PAM50rootlets --> nativeRootletsInPAM50space -- using this one
>registration2_1Warp.nii.gz              # nativeRootletsInPAM50space --> PAM50rootlets 
>registration2_0GenericAffine.mat
>```

I realized that I was not using the affine matrix `registration2_0GenericAffine.mat` produced by the first step of the [`$SCT_DIR/bin/isct_antsRegistration`](https://github.com/ivadomed/model-spinal-rootlets/issues/13#issuecomment-1750678688) command (`--transform Affine[5]`). 
Why? Because I initially thought the affine transform was included within the `registration2_1InverseWarp.nii.gz`). But apparently, it is not included, and each transform should be treated separately; see [here](https://github.com/ANTsX/ANTs/wiki/Forward-and-inverse-warps-for-warping-images,-pointsets-and-Jacobians#terminology).

Now, when manually including the affine in the `sct_concat_transfo` command to produce the final warping field (`warp_final_including_affine.nii.gz`):

```console
# Note that `-winv` is used to invert the affine transform
$ sct_concat_transfo -d ${file_t2}.nii.gz -w registration2_0GenericAffine.mat registration2_1InverseWarp.nii.gz warp_template2anat.nii.gz -o warp_final_including_affine.nii.gz -winv registration2_0GenericAffine.mat
```

And warping PAM50 spinal levels (`template/PAM50_spinal_levels.nii.gz`) to subject native space:

```console
$ sct_apply_transfo -i ~/code/PAM50/template/PAM50_spinal_levels.nii.gz -d ${file_t2}.nii.gz -w warp_final_including_affine.nii.gz -x nn -o PAM50_spinal_levels_reg_with_affine.nii.gz
```

The warped PAM50 levels (`PAM50_spinal_levels_reg_with_affine.nii.gz`) are now shifted a little bit up:

![Kapture 2023-10-09 at 14 47 09](https://github.com/ivadomed/model-spinal-rootlets/assets/39456460/4f421ea0-2ed5-4499-abd5-5200a6a65583)

But it seems to me that the spinal levels are now too high relative to the vertebrae. See, for example, the C4 level (pink color with the cursor). After the shift up, the C4 level is at the level of disc C2/C3. But it should instead be located at the level of vertebra C3; see illustration [here](https://www.sci-info-pages.com/levels-and-classification/).

**Comment by jcohenadad** [comment] 2023-10-10 19:35
Why do you include two times `registration2_0GenericAffine` with -w in the beginning and -win in the end?
~~~
$ sct_concat_transfo -d ${file_t2}.nii.gz -w registration2_0GenericAffine.mat registration2_1InverseWarp.nii.gz warp_template2anat.nii.gz -o warp_final_including_affine.nii.gz -winv registration2_0GenericAffine.mat
~~~

I would do:
~~~
$ sct_concat_transfo -d ${file_t2}.nii.gz -winv registration2_0GenericAffine.mat registration2_1InverseWarp.nii.gz warp_template2anat.nii.gz -o warp_final_including_affine.nii.gz
~~~

**Comment by valosekj** [comment] 2023-10-11 17:46
> Why do you include two times `registration2_0GenericAffine` with -w in the beginning and -win in the end?

Based on the following [`sct_concat_transfo.py -win` flag help](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/78d46e0d1a75dfa6a27689931bf4111a233c04f1/spinalcordtoolbox/scripts/sct_concat_transfo.py#L132-L135), I understood that the transformation included in the flag `-win` must also be included in the flag `-w`.

```
help='Affine transformation(s) listed in flag -w which should be inverted before being used. Note that this '
     'only concerns affine transformation (not warping fields). If you would like to use an inverse warping '
     'field, then directly input the inverse warping field in flag -w.',
```

This is also confirmed by the `isct_ComposeMultiTransform` call when all three transformations are used:

```console
$ sct_concat_transfo -d ${file_t2}.nii.gz -w registration2_0GenericAffine.mat registration2_1InverseWarp.nii.gz warp_template2anat.nii.gz -o warp_final_including_affine.nii.gz -winv registration2_0GenericAffine.mat

...

Parse list of warping fields...

Check file existence...
  OK: sub-007_ses-headNormal_T2w.nii.gz
  OK: registration2_0GenericAffine.mat
  OK: registration2_1InverseWarp.nii.gz
  OK: warp_template2anat.nii.gz
/Users/valosek/code/sct_latest/bin/isct_ComposeMultiTransform 3 warp_final.nii.gz -R sub-007_ses-headNormal_T2w.nii.gz warp_template2anat.nii.gz registration2_1InverseWarp.nii.gz -i registration2_0GenericAffine.mat # in /Users/valosek/data/data.neuro.polymtl.ca/rootlets_seg/register_to_PAM50
```

---

> 
> I would do:
> 
> ```
> $ sct_concat_transfo -d ${file_t2}.nii.gz -winv registration2_0GenericAffine.mat registration2_1InverseWarp.nii.gz warp_template2anat.nii.gz -o warp_final_including_affine.nii.gz
> ```

When trying this command, I got an error about missing `-w` arg. So I included the flag into the command:

```console
$ sct_concat_transfo -d ${file_t2}.nii.gz -winv registration2_0GenericAffine.mat -w registration2_1InverseWarp.nii.gz warp_template2anat.nii.gz -o warp_final_including_affine_fixed.nii.gz
```

However, `registration2_0GenericAffine.mat` is not used at all!

```console
...
Parse list of warping fields...

Check file existence...
  OK: sub-007_ses-headNormal_T2w.nii.gz
  OK: registration2_1InverseWarp.nii.gz
  OK: warp_template2anat.nii.gz
/Users/valosek/code/sct_latest/bin/isct_ComposeMultiTransform 3 warp_final.nii.gz -R sub-007_ses-headNormal_T2w.nii.gz warp_template2anat.nii.gz registration2_1InverseWarp.nii.gz # in /Users/valosek/data/data.neuro.polymtl.ca/rootlets_seg/register_to_PAM50
```

**Comment by RaphaSchl** [comment] 2023-10-23 14:06
Hey Jan, these advances are really exciting !

I also think you have to add `registration2_0GenericAffine.mat` in both `-w` and `-winv` when using `sct_concat_transfo,` to indicate that you want this matrix inverted when concatenated.  
But in this last try here, it seems to not have been used at all because you forgot to add it in `-w` .
> When trying this command, I got an error about missing -w arg. So I included the flag into the command:
> $ sct_concat_transfo -d ${file_t2}.nii.gz -winv registration2_0GenericAffine.mat -w registration2_1InverseWarp.nii.gz warp_template2anat.nii.gz -o warp_final_including_affine_fixed.nii.gz
> However, registration2_0GenericAffine.mat is not used at all!

 Have you tried : 
` $ sct_concat_transfo -d ${file_t2}.nii.gz -winv registration2_0GenericAffine.mat -w registration2_0GenericAffine.mat registration2_1InverseWarp.nii.gz warp_template2anat.nii.gz -o warp_final_including_affine_fixed.nii.gz`

Let me know how this goes !

**Comment by valosekj** [comment] 2023-11-02 16:14
Thank you, Raphaelle!

> Have you tried :
 `$ sct_concat_transfo -d ${file_t2}.nii.gz -winv registration2_0GenericAffine.mat -w registration2_0GenericAffine.mat registration2_1InverseWarp.nii.gz warp_template2anat.nii.gz -o warp_final_including_affine_fixed.nii.gz`

Yes, I have tried! And indeed, this is the right command to concatenate all transformations. In other words, `registration2_0GenericAffine.mat` has to be included in both `-w` and `-winv`.

For clarity, I put all the commands discussed in this thread into a bash script (see [here](https://github.com/ivadomed/model-spinal-rootlets/blob/jv/refactor_utilities_folder/utilities/bring_PAM50_spinal_levels_to_native_space.sh)).

However, I noticed that the [label-wise Tz-only registration](https://github.com/ivadomed/model-spinal-rootlets/blob/jv/refactor_utilities_folder/utilities/bring_PAM50_spinal_levels_to_native_space.sh#L55-L59) does not work well in some subjects --> I'm investigating that!

**Comment by valosekj** [comment] 2024-10-02 15:23
Closing this issue as the follow-up investigation continues in https://github.com/ivadomed/model-spinal-rootlets/issues/78.

**Closed by valosekj** 2024-10-02 15:23 UTC
